### PR TITLE
API improvements

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

- Moved all serializer configurations from YAML to annotations
- Includes some BC breaks, please read UPGRADING.md
- Smoothed out inconsistencies, unfortunately some minor BC breaks had to be introduced
- Removed attributes order (BC break if you intentionally mis-used the JSON structure)
- All duplicate result types (Team2, Team3, Activity2...4 ...) could finally be removed (needs refactoring if you used swagger generated code!)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
ping @hmr-it-jr @kbancerz @infeeeee @ AlexandrePTJ please take some time and test these changes before the next release, your integrations might run into issues. I tried hard to avoid API BC breaks, but you can never know if something slipped through...
The API had to be refactored, as it grew "out of control" and had some massive pain points that needed to be cleared out.

**Comment by hmr-it-jr** [comment]
Hi @kevinpapst thanks for notifying. I've tested my app with master after you've merged this PR and everything is still working 🎉 so good job 👍

**Comment by kevinpapst** [comment]
Thanks!
But you are not using all the team/rate/user routes, are you?
Waiting for @kbancerz to hopefully reply soon.

**Comment by hmr-it-jr** [comment]
Yes, I don't use these routes.

**Comment by AlexandrePTJ** [comment]
Hi @kevinpapst, thanks for the notification. Kemai still working great. (Tested on dev online demo)

**Comment by kevinpapst** [comment]
Thanks for the feedback!!!

**Comment by infeeeee** [comment]
Everything is working as before the update, tested on demo, I don't use these routes. Thank you for the ping!

**Pull request merged**
