### PR TITLE
Switch for plugin tests

### PR DESCRIPTION
**Pull request by tobybatch**
## Description
Allows tests in plugins to be included/excluded using a switch in the phpunit.xml.dist

## Types of changes
- [ X Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [X] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by tobybatch** [comment]
@kevinpapst I'll close the othe rone, I mis-understood

**Comment by tobybatch** [comment]
I think this is OK.  There is reliance on the plugin developer to accept passing failing tests in core if the plugin messes with them.  I think that's ok.

**Comment by kevinpapst** [comment]
Yeah, you say that now ... that was my initial thought as well and then I wasted multiple times "hours" by searching for the damn bug, which wasn't really existing :-D

**Comment by kevinpapst** [comment]
Btw. I'd rather start with removing it altogether and see where we go from there.
Having a PHPUNIT env check in the Kernel feels a bit awkward.
I'll try here with a couple of plugins and see if the errors still exist.

**Comment by tobybatch** [comment]
I tested the other PR with your CSS plugin and my chrome extension one and they both passed OK.

**Comment by kevinpapst** [comment]
Thanks for testing! I have a couple of none published plugins for customers and others which I plan to sell soon, I'll test them as well. Shall we re-open the other PR then? I really like deleting the if better than adding a new env.

**Comment by tobybatch** [comment]
Yes, we should.  And close/delete this one if you want to.

**Comment by kevinpapst** [comment]
Closing in favour of #864

**Pull request closed without merging**
