### PR TITLE
Add Weekly report for all users in Reporting page

### PR DESCRIPTION
**Pull request by theapu**
## Description
This update adds Weekly report for all users in Reporting page.

Docu PR: https://github.com/kimai/www.kimai.org/pull/78

## Types of changes
- [x] New feature - Added Weekly report for all users in Reporting page.

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [x] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Very nice, thanks a lot for the contribution @theapu 👍 

Looks very good, I have one minor comment regarding the consistency of translation keys and route names - but I want to test it locally first, before leaving a review.

Please give me some days, my project pipeline is quite full currently.

**Comment by bkcberry** [comment]
Is there a way i can add this to my installation now?

**Comment by theapu** [comment]
> Is there a way i can add this to my installation now?

Please install CustromReportBundle plugin.
https://github.com/theapu/Kimai-CustromReportBundle/releases/tag/v1.0

**Comment by bkcberry** [comment]
Thank you!

**Comment by kevinpapst** [comment]
Big thank you for the PR and big sorry for not merging it earlier.

A lot of internals in the reporting module changed and I unified a lot of the codebase.
In that process I added the report in PR #2494

I am closing this as duplicate, sorry ... totally my bad 😢

**Pull request closed without merging**
