### PR TITLE
Timesheet Summary

### PR DESCRIPTION
**Pull request by jankowski-michal**
## Description
Preference to show summary for whole searched timesheet records. 
Adds another row to results, similar to the daily summary, but sums all queried records.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Hi @jankowski-michal and thanks for the contribution!
Does that sum up the entries on the first page or of all records / all pages?

**Comment by jankowski-michal** [comment]
The sum is for all records on all pages, there is also information of dates from-to as on screenshot

Selection_027

**Comment by kevinpapst** [comment]
In that case let me get straight to the point: we can't use it like that.  It might work for your use case, but what if someone has tenth of thousand of entries (yes, bigger customers reach these numbers easily)? 

Do you really want to fetch ALL records with all joined elements only to calculate one value? 
Or would you rather build an explicit database query targeted to that specific feature?

If you want to displayed the money as well, then you need to take care of the different customer currencies as well.

And why did you change so many (unrelated) translations? Do you speak all these languages?
Please let's talk about each feature briefly, before implementing it.

**Comment by jankowski-michal** [comment]
Ad. Or would you rather build an explicit database query targeted to that specific feature?
You're right, I'll update it.

Ad. If you want to displayed the money as well, then you need to take care of the different customer currencies as well.
I'll remove currencies.

Ad. And why did you change so many (unrelated) translations? Do you speak all these languages?
Sorry, it was rebase issue. Will update.

**Comment by jankowski-michal** [comment]
I'll close this review and create another one because intellij idea still reformats translation files.

**Pull request closed without merging**
