### PR TITLE
Timesheet Summary

### PR DESCRIPTION
**Pull request by jankowski-michal**
## Description
Preference to show summary for whole searched timesheet records.
Adds another row to results, similar to the daily summary, but sums all queried records.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by jankowski-michal** [comment]
@kevinpapst Any thoughts on this PR?

**Comment by kevinpapst** [comment]
Sorry, I know this is frustrating to wait for so long. I really appreciate your input! 
But currently I don't have the time to check all the open PRs.
I am trying to work through them one by one for the next release and then I will get back to you.

**Comment by jankowski-michal** [comment]
Thanks fo fast answer. Sure, take the time you need :)

**Comment by kevinpapst** [comment]
I am not going to merge this PR, sorry! 
I know this is a bummer, but this feature needs to be rewritten and I don't know how.
All I know: this is not how I want it. 

But big thanks for your contribution 💯 times 👍

**Pull request closed without merging**
