### PR TITLE
Add css class for custom fields plugin item in timesheet list 

### PR DESCRIPTION
**Pull request by andreaspollak**
## Description
Adds css class for custom fields plugin (MetaFieldsBundle) item in timesheet list. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Review by kevinpapst — APPROVED** [review]
This line is even better than the one I linked 😁

**Comment by kevinpapst** [comment]
thanks @andreaspollak !

**Comment by kevinpapst** [comment]
Do you think someone could need those classes in the other listing screens (customer, project, activity) as well?

**Comment by andreaspollak** [comment]
I think it's useful. You'll have more control over specific custom fields (css, js).

**Pull request merged**
