### PR TITLE
Calendar improvements

### LINKED ISSUE #530: Calendar view: more space for business hours
Hi Kevin,

in the calendar view the business hours (in our case 7am to 5pm) could be have more space as the hours outside.

we suggests the following options:

1. the hours outside the defined business hours are in a non viewable area (behind the header/footer of the calendar) or
2. they could be grouped like 12-6am and 5pm-12am

bildschirmfoto 2019-01-30 um 08 10 59
bildschirmfoto 2019-01-30 um 08 11 24

### LINKED ISSUE #622: Calendar: Return to last view after creating a new time entry
**Is your feature request related to a problem? Please describe.**
When creating a new time entry in calendar view (I like the week view most to select start / end time), the page after submitting this entry is always the list view of "My Times".
This is cumbersome if I want to enter many entries via calendar view (I'd like to log my worktime at the end of a workday).

**Describe the solution you'd like**
Load the last view again, after submitting the entry.

**Describe alternatives you've considered**
Two alternatives
- Add a setting to choose the default "My Times" view.
- Open a modal dialog instead of full page form for the time entry, like it is done in the list view. This would probably allow to directly stay on the page.

**Additional context**
Using Firefox 65.0.1 on an Ubuntu-based Linux system.

### LINKED ISSUE #704: calendar week timesheet task with duration=true error 500
when creating a new task from the week calendar view with 

        duration_only: true

i get this error :

500: Internal Server Error

It does not happen when this configuration is set in the local.yaml file :

duration only: false

And it does not happen from the month calendar.
And what also happens when creating a task from the month calendar always starts at 10:00.
But in the local.yaml it is configured like this :

    calendar:
        week_numbers: true
        day_limit: 4
        businessHours:
            days: [1, 2, 3, 4, 5]
            begin: '08:00'
            end: '20:00'

**Logfile**

[2019-04-14 13:40:00] request.INFO: Matched route "timesheet_create". {"route":"timesheet_create","route_parameters":{"_route":"timesheet_create","_controller":"App\\Controller\\TimesheetController::createAction","_locale":"es"},"request_uri":"http://localhost/kimaidurasemana/public/es/timesheet/create?origin=timesheet","method":"POST"} []
[2019-04-14 13:40:00] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2019-04-14 13:40:00] php.INFO: User Deprecated: Checking for the AdvancedUserInterface in "Symfony\Component\Security\Core\Authentication\Token\AbstractToken::hasUserChanged()" is deprecated since Symfony 4.1 and support for it will be removed in 5.0. Implement the Symfony\Component\Security\Core\User\EquatableInterface to check if the user has been changed, {"exception":"[object] (ErrorException(code: 0): User Deprecated: Checking for the AdvancedUserInterface in \"Symfony\\Component\\Security\\Core\\Authentication\\Token\\AbstractToken::hasUserChanged()\" is deprecated since Symfony 4.1 and support for it will be removed in 5.0. Implement the Symfony\\Component\\Security\\Core\\User\\EquatableInterface to check if the user has been changed, at D:\\xampp\\htdocs\\kimaidurasemana\\vendor\\symfony\\security\\Core\\Authentication\\Token\\AbstractToken.php:265)"} []
[2019-04-14 13:40:00] php.INFO: User Deprecated: Checking for the AdvancedUserInterface in "Symfony\Component\Security\Core\Authentication\Token\AbstractToken::hasUserChanged()" is deprecated since Symfony 4.1 and support for it will be removed in 5.0. Implement the Symfony\Component\Security\Core\User\EquatableInterface to check if the user has been changed, {"exception":"[object] (ErrorException(code: 0): User Deprecated: Checking for the AdvancedUserInterface in \"Symfony\\Component\\Security\\Core\\Authentication\\Token\\AbstractToken::hasUserChanged()\" is deprecated since Symfony 4.1 and support for it will be removed in 5.0. Implement the Symfony\\Component\\Security\\Core\\User\\EquatableInterface to check if the user has been changed, at D:\\xampp\\htdocs\\kimaidurasemana\\vendor\\symfony\\security\\Core\\Authentication\\Token\\AbstractToken.php:265)"} []
[2019-04-14 13:40:00] security.DEBUG: User was reloaded from a user provider. {"provider":"FOS\\UserBundle\\Security\\EmailUserProvider","username":"brienen"} []
[2019-04-14 13:40:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2019-04-14 13:40:01] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2019-04-14 13:40:01] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2019-04-14 13:40:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\InvalidArgumentException: "Expected argument of type "DateTime", "NULL" given." at D:\xampp\htdocs\kimaidurasemana\vendor\symfony\property-access\PropertyAccessor.php line 173 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\InvalidArgumentException(code: 0): Expected argument of type \"DateTime\", \"NULL\" given. at D:\\xampp\\htdocs\\kimaidurasemana\\vendor\\symfony\\property-access\\PropertyAccessor.php:173)"} []
[2019-04-14 13:40:01] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []

 - Device: Notebook
 - OS: Windows10
 - Browser: chrome
 - Version: Versión 73.0.3683.103 (Build oficial) (64 bits)
 - Kimai 0.8.1
 - PHP Version 7.2.16

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

- Calendar is now using modals, so the user will not leave the current screen
- Calendar events can be dragged & dropped (for time & date change)
- Calendar events can be resized (for duration change)
- Calendar reloads data on edit and create record
- Calendar is now a first class citizen in the main navigation 
  - and therefor removed from the timesheet action icons
- Fixes bugs in combination with duration_only mode
- New system setting to configure the visible timeframe in week and day view
- New setting to remove weekends from the calendar
- Now using the Kimai API instead of the custom JSON controller function
- API changes: 
  - datetime format corrected (see comment below)
  - exposing color on collections
  - option to receive the full serialized structure for subresources (currently only for timesheet collection using the URL parameter `full=true`)
- Added system configurations for visibleHours, businessHours, weekends, week_numbers

Fixes #622 
Fixes #530 
Fixes #704

Can be tested at https://demo-branch.kimai.org/

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I ran `bin/console kimai:codestyle --fix` to verify the correct code style
- [x] I have added tests to cover my changes
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by infeeeee** [comment]
Works really nicely! Maybe some of these issues were present in the old calendar, as I don't use this regularly.
- If I modify the end of a ongoing recording in the calendar view it stops the recording, however it not updates on the active recording panel, I get a server error when stopping it from the current panel(as it is already stopped)
- I think the current recording's end should be at the red current time sign. I see the problem, the currently started record would have a 0 height this case. Now it 'overflows' it: 
image
- If I drag a record to the all day in the weekly or daily view I get this error: Changes could not be saved: Validation Failed. What is the point of this all day section? If I make a multi-day record, it doesn't populate this section
- There is no way to delete a record from the calendar view. Maybe a delete button on the edit dialog would be good.
- The height of the calendar changes based on the width of the window. It's strange, that I have a huge monitor but the full month doesn't fit vertically. Is it a setting in the calendar widget? Can this behaviour changed some way?

**Comment by kevinpapst** [comment]
@hmr-it-jr ATTENTION: I found a bug in the timesheet API requests. The format for queries was wrong, still using the "wrong" format. I changed that, [see this diff](https://github.com/kevinpapst/kimai2/pull/784/commits/7c7fcf962d287b5a34e8c3dd21c4fcc6fe102702#diff-6626903cab73c8bd1ec2715fbbe2bc94).

Now it finally works as announced in the documentation. When using a `begin` or `end` filter you must use  `2019-03-02T14:23:00` instead of previously `2019-03-02 14:23`. 

Probably you can add a switch to the App, using the old format for 0.9 and the new for 1.0?

**Comment by hmr-it-jr** [comment]
@kevinpapst one question: is this really

> 2019-03-02T14:23:00

correct?

Because in my time framework (moment.js) provides only this:

```
2019-05-19T10:24:03+02:00
```

so I assume the correct version of the quoted one above should be:

```
2019-03-02T14:23:00+00:00
```

------------

Of course I can make a check of the verison of the api before sending any tracked times and convert the tracked times into the correct format. I just hope we don't change it with every Kimai release 😄

**Comment by kevinpapst** [comment]
LOL, no plans to change it again, unless someone finds another bug ^^

Don't use plain `moment.format()` but as [shown here](https://www.kimai.org/documentation/rest-api.html#datetime-formats-iso-8601-and-html5): `moment.format(moment.HTML5_FMT.DATETIME_LOCAL_SECONDS)`

**Comment by hmr-it-jr** [comment]
@kevinpapst I've tested the new format
```javascript
moment().format(HTML5_FMT.DATETIME_LOCAL_SECONDS);
```
but the new format worked for me on my outdated 0.9, demo.kimai.org and demo-branch.kimai.org

My local kimai with request /api/verison returns
```json
{
    "version": "0.9",
    "candidate": "stable",
    "semver": "0.9-stable",
    "name": "Ayumi",
    "copyright": "Kimai 2 - 0.9 stable (Ayumi) by Kevin Papst and contributors."
}
```

Is there something for me to do then which I don't see?

**Comment by kevinpapst** [comment]
The demo sites are already updated, please try the `-stable` domain.
It didn't work for me with the `T` separator instead of ` ` but I was sure that I tested it before releasing 0.9.

**Comment by hmr-it-jr** [comment]
Hm, it works for me.

**Request:**
grafik

**Response:**
grafik

**Comment by kevinpapst** [comment]
Well, if the app still works with demo.kimai.org and demo-stable.kimai.org then there is no change necessary ... what would be even better!

**Pull request merged**
