### PR TITLE
Import groups

### PR DESCRIPTION
**Pull request by HonzaKopecky**
## Description
Data import from Kimai v1 now imports groups that are represented as Teams in the new Kimai. Import will connect Teams with users, customers, projects and customers assigned to projects. The import doesn't process relations between groups and activities as this is not supported in Kimai 2.

The import will skip groups that have no members. The import will always assign a teamlead to the project. If none of the users in Kimai v1 was assigned as the teamlead, the first member of the group is assigned as teamlead during import. The groups that were trashed in Kimai v1 are not imported into Kimai 2 as hidden/trashed teams are not supported.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by HonzaKopecky** [comment]
## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [x] I updated the documentation: https://github.com/kimai/www.kimai.org/pull/59
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

**Comment by kevinpapst** [comment]
Thanks @HonzaKopecky ! 
I recently added importing of user specific rates, can you please merge master.
And I assume that linting will fail, as you use `==` operator, inserted of `===`.
You can run `composer kimai:codestyle` and `composer kimai:codestyle-fix` locally.

**Comment by HonzaKopecky** [comment]
Merged master. But linter doesn't complain at all. I ran kimai:codecheck with the following output:
```
> vendor/bin/php-cs-fixer fix --dry-run --verbose --show-progress=none
Loaded config default from "/home/honza/kimai-new/.php_cs.dist".
Using cache file ".php_cs.cache".
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle/>
```

And I also ran kimai:pre-commit and all tests passed.

```
> vendor/bin/php-cs-fixer fix --dry-run --verbose --show-progress=none
Loaded config default from "/home/honza/kimai-new/.php_cs.dist".
Using cache file ".php_cs.cache".
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle/>
> vendor/bin/phpstan analyse src -c phpstan.neon --level=4
 517/517 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] No errors

> vendor/bin/phpstan analyse tests -c tests/phpstan.neon --level=4
 283/283 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] No errors

> bin/console lint:yaml config --parse-tags

 [OK] All 58 YAML files contain valid syntax.

> bin/console lint:twig templates --show-deprecations

 [OK] All 125 Twig files contain valid syntax.

> bin/console lint:xliff translations

 [OK] All 261 XLIFF files contain valid syntax.

> bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

Mapping
-------

 [OK] The mapping files are correct.

Database
--------

 [SKIPPED] The database was not checked for synchronicity.
> vendor/bin/phpunit --exclude-group integration tests/
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Testing tests/
.............................................................   61 / 1133 (  5%)
.............................................................  122 / 1133 ( 10%)
.............................................................  183 / 1133 ( 16%)
.............................................................  244 / 1133 ( 21%)
.......................SSSS..................................  305 / 1133 ( 26%)
.............................................................  366 / 1133 ( 32%)
.............................................................  427 / 1133 ( 37%)
.............................................................  488 / 1133 ( 43%)
.............................................................  549 / 1133 ( 48%)
.............................................................  610 / 1133 ( 53%)
.............................................................  671 / 1133 ( 59%)
.............................................................  732 / 1133 ( 64%)
.............................................................  793 / 1133 ( 69%)
.............................................................  854 / 1133 ( 75%)
.............................................................  915 / 1133 ( 80%)
.............................................................  976 / 1133 ( 86%)
............................................................. 1037 / 1133 ( 91%)
............................................................. 1098 / 1133 ( 96%)
...................................                           1133 / 1133 (100%)

Time: 7.36 seconds, Memory: 56.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 1133, Assertions: 4652, Skipped: 4.

Remaining direct deprecation notices (8)

Remaining indirect deprecation notices (1)

Legacy deprecation notices (8)
```

**Comment by kevinpapst** [comment]
Weird, I would have sworn that the linter tests for strict equality checks. But anyways, the code style it not the important part of this PR ;-)

I do not have a Kimai 1 database with groups (and I never used that feature in v1, so I cannot test the changes. I assume you ran it successful against your installation?!

**Comment by HonzaKopecky** [comment]
Well, let's keep it consistent. I fixed the strict comparisons.

**Comment by HonzaKopecky** [comment]
And yeah, of course, the import works on our Kimai v1 data with groups.

**Comment by kevinpapst** [comment]
Thanks @HonzaKopecky

**Pull request merged**
