### PR TITLE
fix url under certain environments

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

Fixes https://github.com/tobybatch/kimai2/issues/269

@praul can you please test this change and let me know if it fixes our issue?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by praul** [comment]
Hi, thanks for the quick fix. I am going to try this out by replacing the files in a running container.
Cloning this repo, merging the pull request and building a docker image would be somewhat over my head right now :)

**Comment by tobybatch** [comment]
Thanks @praul This will be rolled into the images next release.

**Comment by praul** [comment]
The fix works. Thanks a lot!

**Review by praul — APPROVED** [review]
Successfully fixes https://github.com/tobybatch/kimai2/issues/269

**Comment by kevinpapst** [comment]
Thanks @praul for testing!

**Pull request merged**
