### PR TITLE
Update to Symfony 4.2

### LINKED ISSUE #685: Infinite loading when entering settings or editing a customer
**Describe the bug**
Entering the system configuration page or customer edit page results in infinite loading and eventually a timeout. The `php-fpm` generates high CPU usage in the meantime. The memory usage increases during this process.

**To Reproduce**
1. Go to `System Settings` or `Edit a Customer`
2. Infinite loading

**Logfile**
```
[2019-04-08 18:59:39] php.CRITICAL: Fatal Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 268435464 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 268435464 bytes) at /caddy/kimai/app/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php:134)"} []
[2019-04-08 18:59:39] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 268435464 bytes)" at /caddy/kimai/app/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php line 134 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 268435464 bytes) at /caddy/kimai/app/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php:134)"} []
```

**Logfile (Server/php-fpm)**
```
08/Apr/2019:20:56:59 +0200 [ERROR 504 /index.php] read unix @->/run/php-fpm/php-fpm.sock: i/o timeout
```

There doesn't seem to be a very helpful error message. I increased the memory limit to 2GB, but it just takes longer to get to the exception.

**Additional context**
 - Kimai version: 3a4aa5a0012dd0f79caeb947803fe8adc8509dc1
 - PHP version
```
PHP 7.3.4 (cli) (built: Apr  5 2019 12:40:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
```
- Web server: Caddy
```
http://kimai.local {
    bind 127.0.0.1
    bind ::1
    root /caddy/kimai/app/public
    timeouts none
    fastcgi / unix:/run/php-fpm/php-fpm.sock php {
        env APP_ENV prod
        env APP_SECRET kimai2
        env DATABASE_URL mysql://kimai:kimai@127.0.0.1:3306/kimai
        env MAILER_FROM bot@kimai.local
        env MAILER_URL smtp://127.0.0.1:25/
        env SQL_PROTOCOL mysql
        connect_timeout 120s
        read_timeout 180s
        send_timeout 180s
    }
    rewrite {
        to  {path} {path}/ /index.php?_url={uri}
    }
    errors /caddy/kimai/error.log
    header / -Server
    header / -X-Powered-By
}
```

I double checked file permissions to be absolutely sure its not a permission related problem.

I also tried an older version, but I have the same issue. Not sure what is going on there.

It works in the docker container, but I want to migrate kimai to the host system as I'm interested into contributing to the project.

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #685

### CODE REVIEW

**Comment by magiruuvelvet** [comment]
I tested this PR on Arch Linux with PHP 7.3 and the hangs are gone and it mostly works now. There is still a problem with the API(?). When adding a new task it shows absolutely everything and all activities from all customers and projects. Is there some kind of filter which is broken on PHP 7.3 perhaps?

Other than that I didn't notice any other issues. Rolling back to my docker container for now as this is a mayor problem and can mess with the database I think.

**Comment by kevinpapst** [comment]
Thanks for your feedback! 
Can you describe what you did exactly, as I don't get what you did:
> When adding a new task it shows absolutely everything and all activities from all customers and projects
What is a task? One timesheet record? And what do you mean with "is dhows absolutely everything"? Where does it show that?

**Comment by magiruuvelvet** [comment]
By task I mean creating a timesheet record. And in the drop down for projects and activities it always shows everything regardless of what is selected in the previous dropdown. When making an API request directly with curl I also get everything back which shouldn't be there.

**Comment by kevinpapst** [comment]
Hm, indeed - thats weird and shouldn't happen. I'll have a look. Thanks for the clarification!

**Comment by kevinpapst** [comment]
@magiruuvelvet I updated to the yesterday released Symfony v4.2.7. I haven't tried the commit before, but that one doesn't have the described problems for me. And to be honest, I don't know how that should even be possible what you described. Not that I don't believe you, its just weird.  And there are tests in place which check the result from the API calls, so I have to assume that this is a local problem on your machine. Maybe you could try to delete the cache manually via `rm -rf var/cache/*` after switching to this branch and before and after running `composer install`?

**Comment by magiruuvelvet** [comment]
It's so weird and I'm out of ideas myself. It still returns all activities at once. The frontend is sending the correct parameters though.

I removed the cache as you advised and also made a fresh dependency install.

**Comment by kevinpapst** [comment]
Are you sure you are seeing all activities? So in the JSON result there might be activities that don't have a "project" field (global activities) and ones with "project" field. If the "project" field is available, it should be the ID of the request. So if you request /api/activities?project=1 there should be only global activities and the ones with project=1 in the result.

**Comment by magiruuvelvet** [comment]
I don't have global activities. Every project is assigned to a customer and every activity is assigned to a project. It works in PHP 7.2 in the Debian docker container, but not on PHP 7.3 on Arch Linux.

**Pull request merged**
