### PR TITLE
Finnish translations

### PR DESCRIPTION
**Pull request by vilu85**
## Description
Adds finnish translations for Kimai.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] I verified that my code applies to the guidelines (`composer code-check`)
- [X] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [X] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thank you very much @vilu85 👍 

I will have a look soon. Are you going to translate the latest files as well?

**Comment by vilu85** [comment]
> Thank you very much @vilu85 👍
> 
> I will have a look soon. Are you going to translate the latest files as well?

Yes, I'll do that as soon as possible :)

**Comment by vilu85** [comment]
> Thank you very much @vilu85 👍
> 
> I will have a look soon. Are you going to translate the latest files as well?

According to the translation documentation (https://www.kimai.org/documentation/translations.html) I don't need to translate frontend files app.js, calendar.js or moment.js. All files from kimai2/translations is now translated and checks have passed so this pull can be closed as soon as frontend files are upgraded.

**Comment by kevinpapst** [comment]
I changed my mind: I will merge it and you can check it directly on the official demo 😁

**Pull request merged**
