### PR TITLE
Fixes #2975: Memberships are deleted when PATCHed

### LINKED ISSUE #2975: [API] PATCH team members removes existing ones
**Describe the bug**
When team members that are already part of a team get passed in the body of the PATCH method to update a team, they are removed from that team.

**To Reproduce**
Create a team with one member, update it through the API with the same member in the body. The member is then deleted.
```
curl --location --request PATCH 'http://kimai.local/api/teams/774' \
--header 'X-AUTH-USER: [insert API user]' \
--header 'X-AUTH-TOKEN: [insert API token]' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Test jelle",
    "members": [
        {
            "user": 3,
            "teamlead": true 
        }
    ]
}'
```

This is also reproducible on your demo environment:
```
curl --location --request PATCH 'https://demo-stable.kimai.org/api/teams/1' \
--header 'X-AUTH-USER: susan_super' \
--header 'X-AUTH-TOKEN: api_kitten' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "District09",
    "members": [
        {
            "user": 3,
            "teamlead": true
        }
    ]
}'
```
**Logfile**
Not relevant, no error messages

**Additional context**
 - Kimai version: 1.15.6 (but also reproducible on 1.16.5)
 - PHP version: 7.4
 - Device: Ubuntu Laptop, Linux server
 - Browser: Not relevant

### PR DESCRIPTION
**Pull request by Jelle-S**
## Description

When PATCHing a team, the documentation states that passing users
(memberships) replaces all existing members. But when a user that is
already part of a team is passed, he is removed from that team. This
change fixes that issue by first emptying the team (removing all
memberships) if team members are passed through the patch method. Since
doctrine / the entity manager seems to process the inserts before the
deletes, we need to also manually flush the entity manager before saving
the team again, so we don't get duplicate key sql errors.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Hi @Jelle-S - can you please test with the latest master branch. 
I cannot reproduce the issue any longer. 
If you are able to reproduce it, please provide 2 API requests to first a) create the team and then b) patch it.

**Comment by Jelle-S** [comment]
@kevinpapst I can still reproduce this:

Create
```
$ curl --location --request POST 'http://kimai.local/api/teams' --header 'X-AUTH-USER: my_api_user@example.com' --header 'X-AUTH-TOKEN: my_auth_token' --header 'Content-Type: application/json' --data-raw '{
"name": "Test Jelle-S",
"members": [
  {
    "user": 3,
    "teamlead": true
  }
]}'
```
Update
```
$ curl --location --request PATCH 'http://kimai.local/api/teams/[new_team_id]' --header 'X-AUTH-USER: my_api_user@example.com' --header 'X-AUTH-TOKEN: my_auth_token' --header 'Content-Type: application/json' --data-raw '{
"name": "Test Jelle-S",
"members": [
  {
    "user": 3,
    "teamlead": true
  }
]}'
```
After creating the team my user is member of the team.
After the update my user is no longer member of the team.

**Comment by kevinpapst** [comment]
Ups, sorry. I blindly relied on the response in Postman, but that is completely different from the result when I fetch the team entity manually after the PATCH. Will look into it right now.

**Comment by kevinpapst** [comment]
I am closing this PR, as it is a creative solution to the underlying problem 😀 but the real fix is hopefully in #3097

**Pull request closed without merging**
