### PR TITLE
Fixed SV locale date format

### PR DESCRIPTION
**Pull request by Oscariremma**
The Swedish locale didn't have the correct date format. I have fixed this and verified that it works.

## Description
Fixed the Swedish locale date format

## Types of changes
- [x] Added Swedish locale date format

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks @Oscariremma for your contribution!

So you want to use 3 different kind of formats for the date part. 
From my POV that looks disturbing and I don't believe that it improves the UX.

Can you share a link to some documentation about Swedish date formats?

**Comment by Oscariremma** [comment]
Hi @kevinpapst 

I have double checked everything and in general we follow the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) so date_time_type, date_type and date where the same as in EN and didn't need changing. I am sorry for not checking this beforehand. 

But the thing that got me to look in to this in the first place was that when I exported my time table to PDF, the format that was used on the individual entries (date_time) used m-d for the date. In Sweden we never write month before day and when you only write the day and the month we often use a / instead of -. If you want some kind of documentation on this the swedish wikipedia page on [date ](https://sv.wikipedia.org/wiki/Datum) explains how we generally write dates.

So the only change that i feel is needed is to swap the day and month in the date_time format and replace the - with a /.

**Comment by kevinpapst** [comment]
Thanks for double checking this! Looks good to me (if I understand the wiki page correctly).

**Comment by kevinpapst** [comment]
Thank you @Oscariremma 👍

**Pull request merged**
