### PR TITLE
fix typo of japanese translation

### PR DESCRIPTION
**Pull request by nabbisen**
## Description
A typo was found in Japanese translation: x "通過" -> o "通貨"

## Types of changes
- [*] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [*] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Hi @nabbisen & thanks 👍 

I am about to release 1.0 and there are a couple of missing translations, maybe you can add them?
```
$ bin/console debug:translation --only-missing ja 
 ----------- --------------- ----------------------------- ----------------------------- ------------------------------------------ 
  State       Domain          Id                            Message Preview (ja)          Fallback Message Preview (en)             
 ----------- --------------- ----------------------------- ----------------------------- ------------------------------------------ 
   missing    messages        admin_entity.delete_confirm   admin_entity.delete_confirm   This data will be deleted as well! Al...  
   missing    messages        label.timeBudget              label.timeBudget              Time budget                               
   missing    flashmessages   timesheet.locked.warning      timesheet.locked.warning      You are editing an exported record        
   missing    flashmessages   warning                       warning                       Warning                                   
 ----------- --------------- ----------------------------- ----------------------------- ------------------------------------------ 
```

**Comment by nabbisen** [comment]
Hi @kevinpapst 
Sure!
1.0 is marvelous!

**Comment by nabbisen** [comment]
> Hi @nabbisen & thanks 
> 
> I am about to release 1.0 and there are a couple of missing translations, maybe you can add them?
> 
> ```
> $ bin/console debug:translation --only-missing ja 
>  ----------- --------------- ----------------------------- ----------------------------- ------------------------------------------ 
>   State       Domain          Id                            Message Preview (ja)          Fallback Message Preview (en)             
>  ----------- --------------- ----------------------------- ----------------------------- ------------------------------------------ 
>    missing    messages        admin_entity.delete_confirm   admin_entity.delete_confirm   This data will be deleted as well! Al...  
>    missing    messages        label.timeBudget              label.timeBudget              Time budget                               
>    missing    flashmessages   timesheet.locked.warning      timesheet.locked.warning      You are editing an exported record        
>    missing    flashmessages   warning                       warning                       Warning                                   
>  ----------- --------------- ----------------------------- ----------------------------- ------------------------------------------ 
> ```

Hi @kevinpapst 

2 additions were found. I'll translate them as well:

- `messages`
    - `stats.yourWorkingHours`
- `system-configuration`
    - `label.timesheet.mode_duration_fixed_begin`

**Comment by nabbisen** [comment]
I made pull request again and cleaned it up: https://github.com/kevinpapst/kimai2/pull/905

**Pull request closed without merging**
