### PR TITLE
added support for Ante meridiem and Post meridiem format

### LINKED ISSUE #578: Support 12h time format
Is there any way to change the 24h format to 12h format?

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #578 

To activate 12-hour format, you have to change your config:
```yaml
kimai:
    languages:
        en:
            date_time_type: 'yyyy-MM-dd hh:mm a'
            date_time_picker: 'YYYY-MM-DD hh:mm A'
            date_type: 'yyyy-MM-dd'
            date_picker: 'YYYY-MM-DD'
            date: 'Y-m-d'
            date_time: 'm-d H:i'
            duration: '%%h:%%m h'
            time: 'h:i a'
            24_hours: false
```

12 hour format in frontend (and JS datetime picker):
bildschirmfoto 2019-03-05 um 02 39 09

The 24-hour format:
bildschirmfoto 2019-03-05 um 02 38 51

### CODE REVIEW

**Comment by xtremelora** [comment]
@kevinpapst Thanks a lot, I will try this tomorrow as I don't have the chance today.
Thank you for your support.

**Comment by xtremelora** [comment]
@kevinpapst this is only applicable to 0.9x versions right?

I tried on my 0.8 version and the error says that it doesn't recognize time and 24hours variables...

Here a short error sample: _**User Notice: Found invalid "kimai" configuration: Unrecognized options "time, 24_hours" under "kimai.languages.en" ["exception" => ErrorException { …}]**_

**Comment by kevinpapst** [comment]
Yes, it works only with all changes from the Pull request. You cannot simply change the config and expect that everything works. If that would be the case, I would have given you the config directly ;-)
You can either switch to this branch (if you use git) or you have to wait for the next release.

**Comment by xtremelora** [comment]
@kevinpapst I couldn't find the 12-hours branch... Is it available onn master branch now?

**Comment by kevinpapst** [comment]
Yep

**Pull request merged**
