### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by nabbisen**
## Description
I appreciate this great app.
These commits are for adding Japanese translation.

Thanks to:
- https://github.com/kevinpapst/kimai2/pull/732
- https://github.com/kevinpapst/kimai2/issues/731

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I ran `bin/console kimai:codestyle --fix` to verify the correct code style
- [ ] I have updated the [documentation](https://github.com/kimai/www.kimai.org/tree/master/_documentation) accordingly
    ==> It seemed not neccesary.
- [ ] I have added tests to cover my changes
    ==> It seemed not neccesary.
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

==> The error occurred in running `bin/console kimai:codestyle --fix` :

```
.../kimai2/vendor/bin/php-cs-fixer: not found
                                                                                                                       
 [ERROR] Found problems while checking your code styles                                                                 
                                                      
```

## Screenshot examples

Screenshot from 2019-05-12 02-49-22
Screenshot from 2019-05-12 02-49-44

### CODE REVIEW

**Comment by kevinpapst** [comment]
Wow, thanks a lot @nabbisen 👍 May I ask, are you a native japanese speaker?

Someone else started a Japanese translation as well, but is not a native speaker and the PR #687 is not as mature as yours, so I would favor this one here. 
ping @magiruuvelvet any objections?

**Comment by kevinpapst** [comment]
Oh and the code style is just important for code changes, not for translations.

**Comment by nabbisen** [comment]
@kevinpapst 
Yes, I'm a native Japanese speaker.
I'm sorry I missed #687 ...
Thank you about code style.

**Comment by kevinpapst** [comment]
Awesome! Then I will merge yours, thanks a lot for your effort 🎉 

May I ask as you one small favor in addition? Kimai uses a bundle for theming, which includes a handful of translations, especially for the authentication screens. They are already translated to Japanese, but not from a native speaker. 
Could you have a quick look if anything could be improved there?
The japanese source can be found here:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/translations/AdminLTEBundle.ja.xliff

**Comment by nabbisen** [comment]
@kevinpapst
Thank you so much for your merging.
Well, oh, there is.
I couldn't the file, although it has a part to improve.
O.K.
I'll make another pull request.

**Pull request merged**
