### PR TITLE
added version command + api endpoint

### LINKED ISSUE #320: API: Kimai metadata endpoint
**Describe the solution you'd like**
Currently, there aren't any endpoints to determine some metadata about the running Kimai instance. It would be very beneficial to get some data about the currently running Kimai version and other information. Examples:

- Used Database
- Kimai version
- PHP version

**Additional context**
As you know, I'm currently converting [Timeu](https://github.com/bastilimbach/timeu) to support Kimai2 instead of Kimai v1. It would be really helpful to get the version of the running Kimai instance. With the version number, I could verify, that certain API endpoints and functionalities are available . Currently, I use the version number of the swagger API documentation for that use case, which isn't really optimal. I'm not even sure if the version number gets updated on an API change:

```json
  "swagger": "2.0",
  "info": {
    "title": "Kimai 2 - API Docs",
    "description": "REST API description for the Kimai 2 time-tracking software",
    "version": 0.1
  },
```

**Related issues**
#319

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #320 

Adds new API endpoint `/api/version` with example output:
```json
{
    "version": 0.5,
    "candidate": "dev",
    "semver": "0.5-dev",
    "name": "version-name",
    "copyright": "Kimai 2 - 0.5 dev (version-name) by Kevin Papst and contributors."
}
``` 

Adds new command `bin/console kimai:version` with options:
- `--name`
- `--status`
- `--short`

With example outputs:
```bash
$ bin/console kimai:version
Kimai 2 - 0.5 dev (version-name) by Kevin Papst and contributors.

$ bin/console kimai:version --short
0.5

$ bin/console kimai:version --candidate
dev

$ bin/console kimai:version --semver
0.5-dev

$ bin/console kimai:version --name
version-name
```

ping @anmol26s / @bastilimbach maybe interesting for you?

### CODE REVIEW

**Comment by bastilimbach** [comment]
I just tested the API. Works flawlessly 👍 Maybe you could change the type of `version` to a Float or Double instead of a String.

**Comment by bastilimbach** [comment]
This would of course limit version names to numbers. So a `0.5-rc` version wouldn't be possible.

**Comment by kevinpapst** [comment]
The `-rc` would never be included in the `version` field, only in `status`.
You can definitely rely on casting the value and comparing it. 

What I will do:
- think about changing it to `float`
- renaming `status` to `candidate` or something else which fits better

**Comment by bastilimbach** [comment]
Ok. I'll cast it myself for now 👍

**Comment by kevinpapst** [comment]
@bastilimbach updated API - see adjusted examples in the initial comment. will merge it tomorrow.

**Pull request merged**
