### PR TITLE
Fix english translation for 'info'

### PR DESCRIPTION
**Pull request by trentks**
## Description
In english, 'information' and its shortened form 'info' are their own plurals. Simple spelling change.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [X] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [X] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks @trentks  👍

**Comment by kevinpapst** [comment]
Pleas let me know if you find other weird translations, I am doing my best, but its not my mothers tongue...

**Comment by trentks** [comment]
Hi @kevinpapst,

Just read through the whole translations file... and submitted #1002. There is one error that I found in the web-files that I can't see how it arises in the translation file. See the screenshot below:
2019-08-02-113414_1919x1079_scrot

On the "Administration->Tags" page... it says at the top "Tags allow, to freely combine timesheet records into a resultset". Just replacing the comma with " you" would be enough... but otherwise a better sentence might be "Tags allow for the free combination of timesheet records into a result set".

Cheers, Trent.

**Comment by kevinpapst** [comment]
Hi @trentks ,
actually there is not only messages.en.xliff, but every file in the translation directory that ends with **.en.xliff** could need a checkup. The tags sentence for example can be found here: 
https://github.com/kevinpapst/kimai2/blob/master/translations/tags.en.xliff

**Pull request merged**
