### PR TITLE
[WIP] i18n: initial japanese translation

### PR DESCRIPTION
**Pull request by magiruuvelvet**
## Description
Adds Japanese translations to Kimai2. The translation is not yet complete.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I have executed `bin/console kimai:phpcs --fix` to make sure my changes adopt the correct code style
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Awesome, looking forward to test the final version (even if I won't be able to understand it).
What about date formats, timepicker and so on? Let me know if you need any help.

**Comment by magiruuvelvet** [comment]
I translated most words and simple phrases by now. Calendar is also in Japanese (is this a dependency?). I have some trouble figuring out where the login screen translations are stored. Are they located in a different package?

Translating whole sentences will take me a bit more time as I'm no Japanese native speaker :smile:

The most used interfaces are translated up to 98% already.

**Comment by kevinpapst** [comment]
Calendar is an external JS library, the translations in there should work out of the box.
The authentication screen translations are used from this bundle AFAIR: https://github.com/kevinpapst/AdminLTEBundle
So you would have to create another PR for a file in here:
https://github.com/kevinpapst/AdminLTEBundle/tree/master/Resources/translations

**Comment by magiruuvelvet** [comment]
I added translations to the AdminLTE Bundle here https://github.com/kevinpapst/AdminLTEBundle/pull/58

**Comment by kevinpapst** [comment]
Are you still working on this @magiruuvelvet ? I could include it in 0.9, but this is still marked as Draft.

**Comment by magiruuvelvet** [comment]
It's not finished. I don't know if you want to merge incomplete translations though and if I should open another PR for the remaining strings.

**Comment by kevinpapst** [comment]
Depends ... do you have a rough idea when you will have the time to finish it?

**Comment by magiruuvelvet** [comment]
In my spare free time I guess at least one more month.

**Comment by kevinpapst** [comment]
Ok, then I will postpone it for 1.0.

There are some PRs with translation changes waiting, I will adapt the changes in your branch once I merged them and give you an update.

**Comment by kevinpapst** [comment]
He, sorry to say, but #774 was integrated - Japanese translations by a native speaker. 
If you want, you could have look at the latest master and check if this PR is obsolete.

**Comment by magiruuvelvet** [comment]
the other translation is more complete than mine, so this PR becomes obsolete

**Comment by kevinpapst** [comment]
Sorry for the wasted time... and thanks for the contributions 🥇 , even if it didn't find the way in to the codebase this time

**Pull request closed without merging**
