### PR TITLE
Testing: horizontal forms

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

How horizontal forms could look like in Kimai.
Currently only activated in activities and timesheet edit form for testing.

Please vote or leave your feedback if you think that could be useful.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [ ] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by rarvin** [comment]
How does one see horizontal forms

**Comment by kevinpapst** [comment]
Once I am finished with the Team permissions, I can deploy that on the demo site.

**Comment by rarvin** [comment]
Thank you please let me know once you do it.

**Comment by kevinpapst** [comment]
Closing here, as the horizontal forms will be used with #1046

**Pull request closed without merging**
