### PR TITLE
respect users timezone when populating working-time dashboard widget

### LINKED ISSUE #987: Dashboard incorrect timezone (histogram only)
**Describe the bug**
I live in UTC+12 (New Zealand), my workday is usually from 08:30 local to 17:00 local, or 20:30 UTC to 05:00 UTC. At around 12:00 local (00:00 UTC) the histogram will start populating the next days bar—or I should really say the current days bar (local time), prior to 12:00 local it populates the previous days bar. All other times are accurate however and take account of local timezone (both on the dashboard, and across all other aspects—calendar, etc, as far as I can tell).

**To Reproduce**
1. Have a timezone sufficiently different to UTC.
2. Browse to Dashboard
3. Dashboard splits a day across two days.

**Screenshots**
An example taken at 2019-07-26 16:21:09 local. You will note that the histogram is incorrect, the working hours today shows 05:59h, but the histogram shows only 3:56h, this is because the remaining 2:03h were assigned to the previous (2019-07-25 date).

Do note also, that 2019-07-21 was a Sunday, and not only did I not work that day—but I hadn't even yet installed Kimai, I installed Kimai on 2019-07-22.

Here is a listing of my todays time recording (minus customers/project/rate/etc fields). This image was taken at 2019-07-26 16:27:43 local. I recognise that your current working task doesn't populate through to the dashboard until it is finished.

**Additional context**
 - Kimai version 1.1 (bug existed on 1.0 too)
 - PHP version 7.2.19-0ubuntu0.18.04.1

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

Fixes #987 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by trentks** [comment]
Hey @kevinpapst,

What's your recommended way to pull a test branch? I've treated it like a standard 'release' update, and put it into prod as follows (based on your [update faq](
https://www.kimai.org/documentation/updates.html)):

```
sudo systemctl stop apache2
cd /var/www/kimai2
git fetch origin pull/988/head:working-widget-timezone
git checkout working-widget-timezone
sudo -u www-data composer install --no-dev --optimize-autoloader
sudo -u www-data bin/console cache:clear --env-prod
sudo -u www-data bin/console cache:warmup --env=prod
sudo systemctl start apache2
```

I skipped the last database migration step `bin/console doctrine:migrations:migrate` as I didn't think it were necessary.

After having performed these steps, the existing data entries into the dashboard are still incorrect, and I won't know until tomorrow whether or not new entries will be correct or not (as it's after 00:00 UTC here when I implemented this change).

**Comment by kevinpapst** [comment]
You are right, there is one more problem in the SQL query. I'll check how to fix that.

**Comment by kevinpapst** [comment]
@trentks can you give it another try?
Btw. your installation way looks good

**Comment by trentks** [comment]
Hi @kevinpapst,

I believe that this works. I will double confirm tomorrow, but for now it seems to do the trick.

Thanks for your efforts.

**Comment by kevinpapst** [comment]
Let me know your test results, so I can merge it.
Please note: this PR also imprves the calculation for over-night tasks and splits records into times for each day. Maybe you can have a quick look at that as well.

**Comment by trentks** [comment]
Hi @kevinpapst,

I can confirm that this pull does indeed fix up the dashboard histogram, in-so-far as the original identified issue in #987. As such I will close out that issue.

I will leave a task running overnight tonight to test your additional improvements mentioned, and get back to you tomorrow.

Thanks again for all your efforts. I'm quite enjoying this software, and I think you've done an excellent job in creating it.

**Comment by trentks** [comment]
Patch tests good @kevinpapst. Ready for merge to master.

**Comment by kevinpapst** [comment]
Awesome team work 🎉 thanks @trentks

**Pull request merged**
