### PR TITLE
added table ordering

### LINKED ISSUE #543: Sorting in various tables/pages like User, Customer, Project & Activities
**Describe the solution you'd like**
Make the columns sorteable on those pages. For example by clicking on the 'name' column to get it sorted asc. or desc.

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

Adds table sorting via header click.

Can be tested at https://demo-branch.kimai.org (eg. `susan_super` /  `kitten`).

Please note: you can order by more columns than the ones available in the table. 
When submitting the search form, you see all available URL parameters in your browser URL field. You can, for example, use `id` for sorting, as in:
https://demo-branch.kimai.org/de/admin/activity/?searchTerm=&customer=&project=&globalsOnly=0&visibility=1&pageSize=50&page=1&order=DESC&orderBy=id

You can bookmark these URLs if your workflow requires that sorting.

Fixes #543

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by rarvin** [comment]
@kevinpapst Sorting or ordering works well, but feel the icons used are a bit bigger when compared to the text size. Some tweaking would help.

**Comment by snapet** [comment]
Took a look at the test site and I feel, if possible, it would be better to have the icon on the left of the text. Now it often appears closer to the text referring to the column next to it, which confused me for a second. It's a minor qualm, no show stopper to be honest.
Thanks for the work!

**Comment by hmr-it-jr** [comment]
> Took a look at the test site and I feel, if possible, it would be better to have the icon on the left of the text. Now it often appears closer to the text referring to the column next to it, which confused me for a second. It's a minor qualm, no show stopper to be honest.
> Thanks for the work!

I've tested it too and I share your opinion. This is how it looks like when you sort the description.

grafik

---

grafik

**Comment by kevinpapst** [comment]
Updated demo with icon on the left side and reduced icon size

**Comment by snapet** [comment]
Lovely! Thanks, looking great!

**Pull request merged**
