### PR TITLE
Update italian translations

### PR DESCRIPTION
**Pull request by buoncri**

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks @buoncri 👍 

Unfortunately there is something weird going on, maybe a merge went wrong ... but there are a lot of unrelated files in your PR. Can you clean that up?
The problem is that you are doing your changes on `master` and not in a throw-away-branch.

**Comment by buoncri** [comment]
Thanks, i am not graet in git :-D  i will try made a "it_traslations" branch from your release and  an resend a commit ?

**Comment by kevinpapst** [comment]
As your master looks really weird I'd say: the easiest way for now is to keep a backup of your changes locally, delete your kimai repository/the fork here at Github, fork kimai again and clone your fork locally.
Create a new branch, apply your changes to a new branch. Push that branch and create a PR from it.

In the long run you might be curious how to add a remote and rebase your master on Kimai master, but one step after another ;-) There are great tutorials that explain how to keep your fork up-to-date with an upstream repository.

**Comment by buoncri** [comment]
made another pr more clean :-D

**Pull request closed without merging**
