### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/kimai/messages/) for Kimai - Time tracking/Main application.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by kevinpapst — DISMISSED** [review]

**Comment by kevinpapst** [comment]
ping @eransurg - can you have a look at the updated translations? not that I can read Hebrew, but this looks more like arabic to me ...

**Comment by eransurg** [comment]
@kevinpapst Yes, that's definitely Arabic and not Hebrew

**Comment by kevinpapst** [comment]
Thanks @eransurg , I reverted the changes. 

If you still use Kimai, may I ask you for some support by translating the two missing strings at https://hosted.weblate.org/translate/kimai/messages/he/?q=state:empty ?

**Comment by eransurg** [comment]
@kevinpapst I added my suggestions to the translation.

**Pull request closed without merging**
