### PR TITLE
Custom fields for timesheets, customers, projects and activities

### LINKED ISSUE #697: Add custom fields in timesheet record
I think it may be useful for an administrator to add custom fields to keep track of other values

Example:
we need a custom field to track the number of the lunch tickets used by a person

@kevinpapst have you any idea on how to do it?

### LINKED ISSUE #760: Custom data for external references
**Is your feature request related to a problem? Please describe.**
My use-case is to track IDs of external systems to identify eg. projects, customers, etc...

**Describe the solution you'd like**
I'd like to have a possiblity to add custom data to a record, eg. as JSON.

**Describe alternatives you've considered**
Saving it in the comments :speak_no_evil: 

**Additional context**
Continued from https://github.com/kevinpapst/kimai2/issues/683#issuecomment-489221700

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

Adds new tables and methods to define custom fields for:
- timsheets
- customer
- project
- activity

These fields are internally available and will be exported (if configured as public visible):
- via API
- via spreadsheet export
- via html export
- via (custom) invoice templates

Fixes #760 
Fixes #697 
Related to #497 

These fields can be attached via EventListener, see [documentation](https://github.com/kimai/www.kimai.org/pull/29).

I am planning to build a plugin, which allows to configure the custom fields via UI.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [x] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by delcroip** [comment]
Thank you 

I will check it out in July and get back to you
I still think Kimai is advanced and therefore it will interest people to have the import possibility starting with @isamuse2


br

**Comment by delcroip** [comment]
Hello,

is there a quick way to test or I need to do a git clone + database set up etc ?

br

**Comment by delcroip** [comment]
hello,

 I cannot find how to activate those fiedls on master; did I miss something ? or is it the paid module https://www.kimai.org/store/custom-fields-bundle.html

br

**Comment by kevinpapst** [comment]
Either that or programmatically: https://www.kimai.org/documentation/meta-fields.html

**Pull request merged**
