### PR TITLE
javascript and api to stop and display active records

### LINKED ISSUE #753: Stop entries without page reload
- [ ] The stop entry should be operated via the API, instead of a full page reload. 
- [ ] On success the data-table needs to be reloaded.
- [ ] Trigger an event on stop, that could be fetched by a plugin (active entries dropdown).

### LINKED ISSUE #754: Refactor active entries dropdown
- [ ] Use API to fetch active records
- [ ] Load after page initialization
- [ ] Listen to FE events to initiate reload (e.g. stopped + updated + created + deleted timesheet)

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

- new javascript plugin to render active records
- new API methods:
  - stop timesheet
  - get active records
- stop running records via Javascript
- embedded SweetAlter2 for instant feedback (used for edit in modal, delete, stop)
- fixes #754
- fixes #753 

**Additional changes**
- added system config to switch select-box type via UI
- use datatable macro to render plugin table

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] I ran `bin/console kimai:codestyle --fix` to verify the correct code style
(https://github.com/kimai/www.kimai.org/tree/master/_documentation) accordingly
- [x] I have added tests to cover my changes
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
@infeeeee @hmr-it-jr and everyone else: I'd like to ask you, if you could help me with some testing? This is a follow up on the durations in title issue. Well actually it is much more ... but this was fixed together with all the additional changes mentioned in the PR description. 

I installed the branch at https://demo-branch.kimai.org/ so its simpler to test .

**Comment by hmr-it-jr** [comment]
It works for me:
grafik

grafik

grafik

If the Kimai 2 tab is not focused it works, too. So well done!

**Comment by rarvin** [comment]
Dear Kevin,

I have also done a test through the demo url and can confirm that it works
well.
Tried for multiple tasks the status updates
Tried for individual tasks the status updates
Tried for multiple tasks and then stopped one task in them, could see that
the status of the stopped one vanishes, where as the one active the status
updates.
Tried adding a task when other two are active, the third task also gets
added and its status appears.
Tried adding more than 3 at a time, the notification that three active
tasks are stated is shown, the status is still updated for the 3 tasks
active.
Logged out and logged in and could see the status
Even when the focus of the cursor is not against the said browser screen or
the browser is in the background could see the status updating.

Regards
Aravind

**Comment by kevinpapst** [comment]
Guys, you rock 🎉 thanks for your feedback!

**Pull request merged**
