### PR TITLE
xlsx improvements (#1512)

### PR DESCRIPTION
**Pull request by adrianrudnik**
## Description

Small improvements for the xlsx export as in part requested in #1512. Changes should be fitting to every export that contains a single header row.

## Types of changes

- [ ] Feature: Activated "Auto Filter" feature (as #1512 misnamed it as "table format")
- [ ] Feature: Freeze first row and column for scrolling through larger reports.
- [ ] Feature: Auto size the columns so content fits on screen.

## Checklist

- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

## Remarks

The `composer kimai:code-check` command did not complete successful:

- `phpstan` did reach the memory limit during execution and had to be run with parameter `--memory-limit=512M`. Error message was `PHPStan crashed in the previous run probably because of excessive memory consumption. It consumed around 110 MB of memory.`
- `phpunit` did fail due to `Remaining self deprecation notices (35)` and `Remaining direct deprecation notices (9)`.

after that point I skipped running the code-check.

### CODE REVIEW

**Comment by adrianrudnik** [comment]
Attached resulting xlsx.
[kimai-export (6).xlsx](https://github.com/kevinpapst/kimai2/files/4283607/kimai-export.6.xlsx)

**Comment by kevinpapst** [comment]
NICE! Thanks for that 👍 

I searched everywhere for Pivot tables (which don't work with PHPSpreadsheet). Obviously I was wrong with the wording "pivot table". 
Thanks for mentioning the [AutoFilter hint](https://phpspreadsheet.readthedocs.io/en/latest/topics/autofilters/).

But you are working on a quite old branch. 
Can you please rebase onto current master, so the checks start running.
And you have to move your code to `src/Export/Base/XlsxRenderer.php` during the merge.

**Comment by adrianrudnik** [comment]
Oh boy, something went haywire on the checkout / forking. I will solve it and redo the pull requests ;)

**Comment by kevinpapst** [comment]
Ah, just merge upstream master (or rebase, whatever our prefer).
I'll squash it anyways later

**Comment by adrianrudnik** [comment]
Nope, rebase is not my friend evenings. Closing this, reopening it :D

**Comment by kevinpapst** [comment]
Hahaha, yeah might be a good idea 😁

**Pull request closed without merging**
