### PR TITLE
Danish translations

### PR DESCRIPTION
**Pull request by Badgie**
## Description
Added danish translations

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [x] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Awesome contribution, thanks @Badgie 👍 

I'll try it tomorrow and re-build the frontend assets.

**Comment by Badgie** [comment]
Great! I'll be sure to check in.

One issue of note - I tested it and everything seems to work, except the calendar which, for some reason, is in Turkish. This persists even after removing all Turkish translations, as well as the locales from `.yaml` and `.js` files.

**Comment by kevinpapst** [comment]
This error will go away after you (or me) have rebuild the frontend assets.
If you have the required yarn/node setup, simply run `yarn install` and `yarn run prod`.

**Comment by kevinpapst** [comment]
@Badgie that was a perfect PR 👍  just had to rebuild the frontend assets and everything worked.

Please give it a last test and check the javascript components (eg calendar, dropdown inline search "not found").

**Comment by Badgie** [comment]
Glad to hear it! I rebuilt and tested, and everything works as it should - including Javascript components.

I'm gonna go ahead and create a translation for [AdminLTEBundle](https://github.com/kevinpapst/AdminLTEBundle/tree/master/Resources/translations) as well.
Should I also create a PR at [docs](https://github.com/kimai/www.kimai.org/blob/master/_features/multi-language.md) to reflect the addition?

**Comment by kevinpapst** [comment]
That would be even better :) 
Then I will wait for the AdminLTEBundle update and we can include the composer update as well.
Thanks a lot!

**Comment by Badgie** [comment]
[Done](https://github.com/kevinpapst/AdminLTEBundle/pull/101) and [done](https://github.com/kimai/www.kimai.org/pull/50).
Happy to help!

**Comment by kevinpapst** [comment]
Once again: thanks 🎉

**Pull request merged**
