### PR TITLE
Migrate from zend-ldap to laminas-ldap

### PR DESCRIPTION
**Pull request by sabbelasichon**
Resolves: #1445

EDIT: https://github.com/kimai/www.kimai.org/pull/58 needs to be merged afterwards

## Description
A clear and concise description of what this pull request adds or changes.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [x] I updated the documentation (see https://github.com/kimai/www.kimai.org/pull/58 (https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by sabbelasichon** [comment]
If no one uses the functionality from the old zend-ldap dependency directly everything should be fine. 
Possible this PR could be a BC break.

**Comment by kevinpapst** [comment]
Thats really all? Looks to simple to be true^^ 
I mean, I know MWOP just changed the namespace, but still astonishing...

We need to get the docker crew on board for this change - ping @tobybatch  and @Schrolli91 - the LDAP package has to be changed during the image built. How can we manage to do that?

**Comment by sabbelasichon** [comment]
Yeah, that should be all.

**Comment by kevinpapst** [comment]
> Yeah, that should be all.

"Should" as in "works here", right? 😁

**Comment by sabbelasichon** [comment]
Let me check on monday again. I will test this thoroughly again our LDAP-Server.

**Comment by sabbelasichon** [comment]
Hi, i try it today with my current ldap setup and everything works as expected. What else do we have to change? Let me know what else i can do.

**Comment by kevinpapst** [comment]
Thanks for confirming it works. I need to get feedback from the [docker maintainer](https://github.com/tobybatch/kimai2) first.
Please leave the PR open, I will merge it once all systems are ready for the change.

**Comment by kevinpapst** [comment]
Thanks @sabbelasichon 👍

**Pull request merged**
