### PR TITLE
Added portuguese translations

### PR DESCRIPTION
**Pull request by marquesmatheus**
## Description
Add files for portuguese brazilian translation.

### CODE REVIEW

**Comment by kevinpapst** [comment]
Can you please read this, you have to change two config files as well:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/translations.md#adding-a-new-language

**Comment by marquesmatheus** [comment]
Added these 2 files.

**Comment by kevinpapst** [comment]
Your last commit was wrong. You have to edit the existing files, not add them.
They are now here in the root directory:
https://github.com/marquesmatheus/kimai2/tree/marquesmatheus-patch-1

**Comment by marquesmatheus** [comment]
Sry for the mistake :( ....

**Comment by marquesmatheus** [comment]
I've made the changes on the files!.

**Comment by kevinpapst** [comment]
now you still need to delete the 2 files that were added accidentally ;-)

**Comment by marquesmatheus** [comment]
> now you still need to delete the 2 files that were added accidentally ;-)

Made it! Sry again for this silly mistake.

**Comment by kevinpapst** [comment]
I am really sorry not to see that earlier... but according to the documentation we should use `pt_BR`:
https://symfony.com/doc/current/reference/constraints/Locale.html

I changed it in your branch and already updated the PR, please pull in the latest changes and clear your cache. Then you can test it and should also see the new language in the user-preferences:
bildschirmfoto 2018-11-28 um 14 49 29

**Comment by marquesmatheus** [comment]
Ok man i saw that u made the change! THX 
Other important thin on install steps
" chmod -R g+rw var/"

The permission to var didn't work, for me on debian 9 i changed to chmod -R g+rw /var

Thx again!

**Comment by kevinpapst** [comment]
Why did you close this PR? It hasn't been merged to Kimai.

**Comment by marquesmatheus** [comment]
LOL my mistake.

**Comment by kevinpapst** [comment]
Thanks for the contribution! 👍

**Pull request merged**
