### PR TITLE
duration field in timesheet edit dialog

### LINKED ISSUE #844: Add a "now" button to manual timesheet entry
**Is your feature request related to a problem? Please describe.**
When adding an entry manually, I'm frequently adding an entry for something that just happened. In Kimai v1, this was made easier with the "now" button next to the end time field. This meant that the entry could be told to have finished straight away and then the start time would be manually set.

**Describe the solution you'd like**
As in Kimai v1, a simply now button next to the time field (in the pop up once click on end time) would be the simplest and most elegant solution.

I've attached images of Kimai v1 and one way I could see Kimai v2 implementing this.

Kimaiv1
kimaiv2-example

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

Added. duration field to the timesheet dialog.

Can be tested at https://demo-branch.kimai.org/en/timesheet/

Also adds a "now" button to the calendar icon, fixes #844

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
ping @hmr-it-jr @yayitazale could you have a look if that works as expected? You voted for the `now` button, this PR includes also a new duration field and dependencies between `begin` and `end` field, so make your life a little bit easier (hopefully) 😀 

Bildschirmfoto 2019-10-24 um 17 00 47

**Comment by yayitazale** [comment]
Is this on the dev version of the demo? I can't see it...

**Comment by kevinpapst** [comment]
Sorry 😁 link was in the initial post, here you go: https://demo-branch.kimai.org/en/timesheet/

**Comment by yayitazale** [comment]
Works like a charm.

Thank you.

**Pull request merged**
