### PR TITLE
Tiny fix: use the correct name for the CustomEvent

### PR DESCRIPTION
**Pull request by strouble**
Just a super tiny change. I think it is not intended to use the "un-split" parameter.

### CODE REVIEW

**Comment by kevinpapst** [comment]
Ups, yeah... looks right. I wonder where this is used.
Did you stumble upon that or were you searching for a bug?

**Comment by strouble** [comment]
It is currently not used with more than one event name, so it's currently not a problem, but potentially in the future ...
I am currently looking into a performance improvement, where i could use the custom event and then stumbled across it.

**Comment by kevinpapst** [comment]
Without looking at the code I would have said, that all the API action links are using this code:
https://github.com/kevinpapst/kimai2/blob/master/templates/timesheet/actions.html.twig#L35 (see `data-event` attribute)
I will test and report back

**Review by kevinpapst — APPROVED** [review]
Good finding 👍 mercy

**Pull request merged**
