### PR TITLE
added command to create release packages (for FTP user)

### PR DESCRIPTION
**Pull request by kevinpapst**
Added a command used to create a release package with pre-installed composer, SQLite database and user.

**The package**
The contents of this new package (zip) can be uploaded via FTP and should work out-of-the-box.
This will NOT replace the recommended installation via SSH/git/composer but it can help the people with shared-webhosting.

If you want to help testing, I uploaded a package for `v0.9_dev` to Google drive (~ 81,5 MB): 
https://drive.google.com/open?id=1zbt-X7IkboOTVvzF8fUxj3YnBFsJWAR5

By default it uses a SQLite database, but you should reconfigure your DB connection in `.env` before uploading the files.

:exclamation: ATTENTION :exclamation: You have to point your Webserver to /public/ directory!!!!!!!!
If you see `public/` in the URL do NOT use Kimai, this is a huge security risk, as your database and credentials can easily be downloaded.

**Maintainer only**
This new command is not meant to be used by end-users, but for maintainer only.
The created package could be uploaded to GitHub, to simplify installation process for the "shared Webhosting users" without SSH, Git ... 

Possible commands could looks like this:
```
bin/console kimai:create-release --release 0.8.1 --directory /tmp/
bin/console kimai:create-release --release master
```

**TODO**
- [ ] Write installation documentation

Related to:
- #632
- #494
- #469 
- #199

### CODE REVIEW

**Comment by NicklasAndersson** [comment]
Tried to download the file but did not manage to. Perhaps you could upload it to github?

**Comment by kevinpapst** [comment]
@NicklasAndersson  Unfortunately not, thats what I tried first... GitHub allows 10MB max (unless its a release, what its not).
For the G-Drive download: you have to wait quite a while until you get an error message saying something like "the file could not be scanned for viruses, really want to download?" - then you can download it.

**Comment by NicklasAndersson** [comment]
I have tried the package now. Seems to work great, the only thing i did not like is that it requires a "special" web root setup in apache (on most webhosts).

https://kimai.livsfiloso.fi if you want to do some testing I could setup an account for you

**Comment by fatnmad** [comment]
@kevinpapst thank you so much! 

1. Uploaded zip to web-dir (via plesk)
2. Unpacked (via plesk)
3. Redirected subdomain to /public/
4. Works!

Anything I need to do afterwards? (deleting anything or so?)

**Comment by kevinpapst** [comment]
Thanks for the feedback @NicklasAndersson and @fatnmad 

No cleanup required, but I would highly recommend, that you change your database from SQLite (which is used out of the box) to Mysql => this can be configured in `.env`.

**Comment by fatnmad** [comment]
> No cleanup required, but I would highly recommend, that you change your database from SQLite (which is used out of the box) to Mysql => this can be configured in .env.

sadly it won't work after returning to mysql :/ 
`Authentication request could not be processed due to a system problem.`

**Comment by kevinpapst** [comment]
Only changing the connection string is not enough:
https://www.kimai.org/documentation/installation.html#use-mysql-database
But I see that this documentation is not complete. You would have to change the .env locally and run the `bin/console doctrine:schema:create` command against your hosted database (which requires your DB account to have connection permissions from %).

**Comment by climb4fun** [comment]
Hi Kevin,
first let me thank for this special version. Here my first test results for setup:
1. Setup with SQLite works perfect.
2. Setup with MySQL does not work "500: Internal Server Error". May be a wrong entry from my side in '.env'. MySQL is important for me, have a long history of time recording, which should be migrated to MySQL in Kimai V2. I didn't done what you wrote above for setting up database.
First feedback on application:
1. It is very simple and intuitive. Well done in in every respect.
2. I would like to have lines in Timesheet more narrow like in Kimai V1. I have to set whole month in one screen.
3. I need durations in decimal view - as was in Kimai V1.
Thanks for your outstanding support.
Best
Klaus

**Pull request merged**
