### PR TITLE
xlsx export render don't export decimal duration of timesheet if user…

### PR DESCRIPTION
**Pull request by fredyb**
… preferences 'Use decimal duration in export' is checked #1795 

## Description
A clear and concise description of what this pull request adds or changes.

# Types of changes
- [x] Bug fix (non-breaking change which fixes an issue) #1795
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

Due to a lack of knowledge, I was unable to adapt the phpunit test.

### CODE REVIEW

**Comment by kevinpapst** [comment]
Why did you close this PR?

**Comment by fredyb** [comment]
It was a mishap. How can I open it again?

**Comment by kevinpapst** [comment]
I am afraid that not possible, as you deleted your Kimai fork and the branch altogether.

**Comment by fredyb** [comment]
Ok, will recreate it.

**Pull request closed without merging**
