### PR TITLE
refactored search with free search term support

### LINKED ISSUE #574: Administration > Projects: Input for searching a project
Hi Kevin,

my colleagues missing a input field for searching a project/customer in the filter section at the project/customer administration site.

In our case we have a lot of projects/customers and currently the filter section doesn't contain a field like this. 

(The background is that sometimes my colleagues attach a new project incorrect to a customer and after that they need to search for this project at the project administration site.)

### LINKED ISSUE #667: Customer administration: search field
Hi Kevin,

we added a lot of customers so in the administration view for customers we miss a search field to select customers faster.

Bildschirmfoto 2019-03-29 um 10 45 08

### LINKED ISSUE #926: Selection Field for Customer and Label for Visibility
**Is your feature request related to a problem? Please describe.**
1) Under customer, there is no selection field to quickly browse to a customer (which makes it cumbersome to select a customer for modifications if you have many customers). 
2) Generally, the drop down menu of visibility gives 3 options. However, only option two and three are labeled with "yes" and "no"

**Describe the solution you'd like**
1) Add a selection field "Customer" like it exists under Projects
2) Add a label "both" to the white selection field and maybe move it to the last position

screeshot

### LINKED ISSUE #957: Collecting ideas for custom-fields
This issue should be a collection thread for your ideas regarding custom fields (and please include examples if possible).

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

This PR changes the current filter system:
- adds support for a free search term for all pages
  - `timesheet` - searching in: description
  - `team-timesheet` - searching in: description
  - `customers` - searching in: name, comment, number, contact, email, phone, address
  - `projects` - searching in: name, comment, orderNumber
  - `activities` - searching in: name, comment
  - `tags` - searching in: name
  - `teams` - searching in: name
  - `user` - searching in: username, alias, title, email
- adds support for meta-field queries (with search term like `location:homeoffice`)
- use a dropdown beneath a search input for simpler interaction
- display search form always on desktop
  - use a button to toggle search input on mobile (when "closing" the drop-down the original toolbar is restored)
- drop table auto-reload for changes in filter / search, still existing for entity changes and pagination
- Documentation at https://github.com/kimai/www.kimai.org/pull/37

## TODO

- [x] add search-term field to invoices
- [x] add search-term field to export
- [x] documentation
- [x] tests
- [x] disable javascript enhanced drop-downs in search filters (not working properly)
- [x] remove unused subtitle translations

Fixes #667 
Fixes #574
Fixes #926 
Fixes #957 (only partially, here: filtering custom fields)

Bildschirmfoto 2019-08-26 um 13 45 11
Bildschirmfoto 2019-08-26 um 13 45 33
Bildschirmfoto 2019-08-26 um 13 45 49
Bildschirmfoto 2019-08-26 um 13 46 11

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer kimai:code-check`)
- [x] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by rarvin** [comment]
@kevinpapst Refactored search is very good, but looks wise seems a bit different from the other screens. This is something one can live with. In the timesheet screen the older filtering allowed one to enter the customer name, activity etc etc using autofill javascript which seems to be missing in the new scheme. Having autocomplete is very important when the list is very long. One would have to waste lot of time and if the eyes are not sharp enough might even miss the value one is searching for among the long list. Could you please consider bring in the javascript autofill search. If its too difficult then one could still live with the old scheme for the timesheet screen. On all other screens the current scheme looks okay. Maybe have the old timesheet search look and feel with the added free text search box added in. These are my suggesting. But loosing the javascript search is a big loss.

**Comment by rarvin** [comment]
@kevinpapst could you please load the plugins you have created only demo branches also, since some of the functionality are interlinked and for testing them having demo data as well as the plugins present can help.

**Comment by kevinpapst** [comment]
The plugin demo uses master where search is available: 
https://www.kimai.org/demo/

**Comment by kevinpapst** [comment]
I will have a look at the javascript dropdown plugin, but remember it was always meant as test: 
https://www.kimai.org/documentation/theme.html#searchable-input-types

**Comment by rarvin** [comment]
@kevinpapst Thanks I did a custom metafield search also and it worked as needed. Just one doubt can one use AND OR combinations in the search field like 
location:TVC AND WFH:yes AND booked_in:no 
location:TVC OR WFH:yes OR booked_in:no

or more complex
(location:TVC AND WFH:yes) OR booked_in:no

Something like this

**Comment by rarvin** [comment]
> I will have a look at the javascript dropdown plugin, but remember it was always meant as test:
> https://www.kimai.org/documentation/theme.html#searchable-input-types
> Using multiple dropdowns together is problematic, that why I deactivated them for now. But I will see what I can do.

True, but its simply a great functionality to have around. Makes the tool more functional and modern.

**Comment by rarvin** [comment]
@kevinpapst can a user preference field be searched the same way as one can using the free search toolbar to search by referring to the metafield value.

**Comment by kevinpapst** [comment]
Or searches are not supported, everything is "AND". User-prefs are supported (but only in the user admin screen). Please check the documentation, eg:
https://www.kimai.org/documentation/users.html#filter-and-search
https://www.kimai.org/documentation/timesheet.html#filter-and-search

**Comment by kevinpapst** [comment]
BTW: please open new topics in new issues, otherwise they will be lost in these closed PRs as I cannot keep track of them. Questions which can be answered are okay here, but stuff I need to refer to later on, should be kept in new issues (eg. the javascript dropdowns).

**Pull request merged**
