### PR TITLE
added audit trail for customer, project, activity and timesheet

### LINKED ISSUE #62: Add audit logs
Add automated audit logs

For example:
- https://github.com/DamienHarper/DoctrineAuditBundle

Probably outdated: 
- https://github.com/simplethings/EntityAuditBundle
- https://github.com/xiidea/EasyAuditBundle
- https://github.com/DATA-DOG/DataDogAuditBundle

### LINKED ISSUE #596: create a timeline per activity in the timesheet
**Is your feature request related to a problem? Please describe.**
This issue is not directly related to #224 but it logs manipulations or changes in the timesheet.
I thought about what the lifecycle of an activity is - it's:

- being created
- times added
- times changed
- exported / or in use with an invoice
**and then maybe:**
- marked as not exported
- times changed
- exported again
- ...

Maybe it's possible to add a trigger to the database which stores the changed thing and then the admin or any other role with the permission is possible to view the lifecycle.
The most important information are:

- who has changed it
- when was it changed
- what was changed

**This feature can be used for: projects (when was the project created, ...), activities (change of rates per acitivity, ...), customers, ...., too.**

Then it's perfectly comprehensible what has changed, when has it changed and who did the change.

**Describe the solution you'd like**
Already mentioned above.

In the gui framework AdminLTE there is something called timeline which is perfectly for this. [https://adminlte.io/themes/AdminLTE/pages/UI/timeline.html](https://adminlte.io/themes/AdminLTE/pages/UI/timeline.html) - as a suggestion we can add a "fas info-circle" which opens the lifecycle of the activity, user, project, .... in a modal:
grafik

**Timeline example:**
grafik

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #596 
Fixes #62

**OPEN**
- [x] user tests and feedback
- [x] unit tests for audit functionality and views
- [ ] unit test for App\Twig\EntityExtensions

This PR adds an immutable audit timeline for each the following entities:
- customer
- project
- activity
- timesheet

It does NOT keep track on user entities for privacy reasons.
Linked collections (like activities of the changed project) are not tracked.

Every insert, update and delete event is tracked and all versions of undeleted items can be seen with all changed fields, the author and date-time of the event in each admin section. 
Timesheet audits are only accessible via the team timesheet section but not in "my times".

The following new permissions were added:
- audit_customer,audit_project,audit_activity,audit_own_timesheet,audit_other_timesheet

bildschirmfoto 2019-03-07 um 00 48 55

Refactorings that were done in this PR:
- changed admin controller locations
- changed admin template locations
- unified form labels

Also related to #224

### CODE REVIEW

**Comment by hmr-it-jr** [comment]
@kevinpapst I've tested it and I can confirm that it works.

But I've a question: you use the username to show the user who has created/edited the entry:
grafik

Is it possible for you to change the username?
If I click here to edit the username nothing happens:
grafik

route: 
grafik

**Comment by kevinpapst** [comment]
- added support for user title
- fixed error when a linked item (like activity or project) was deleted

**Comment by hmr-it-jr** [comment]
looks good:
grafik

**Comment by kevinpapst** [comment]
this branch is obsolete, as I improved refactored the plugin system.
the audit trail will be published seperately as plugin.
i will close this PR later on and open a new one.

**Comment by kevinpapst** [comment]
replaced by #623

**Pull request closed without merging**
