### PR TITLE
updated dockerfile

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

See #763 

@tobybatch can you please review?

## Checklist
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by tobybatch** [comment]
@bsumners Yes the refactor has happened.  The docker repo is now building against tagged releases, 0.9 is the latest.  https://github.com/tobybatch/kimai2 or if you just want the images https://cloud.docker.com/u/kimai/repository/docker/kimai/kimai2

@kevinpapst The dev docker in this repo will only change if we need to change the dependencies in it.  That will only happen if we change the OS/PGO set up.

**Comment by kevinpapst** [comment]
So you are saying I shouldn't merge this, as it relies on your base image? 
Or are you saying this is likely the last change we will see in a while?

**Comment by tobybatch** [comment]
Yes, that's fine.  The base image will get pulled from dockerhub if it's needed.  If you want to include it in the kimai2 repo I can add it.

**Comment by kevinpapst** [comment]
I would totally like that!

**Comment by tobybatch** [comment]
Sorry @kevinpapst my local kimai repo is all messed up with the LDAP stuff, here is a gist with the docker file that will build both stages of the dev docker.  I'll fix my repo to use this format for dev later.  If you drop that into your repo it will include the base build.

https://gist.github.com/tobybatch/902ee71f9814239e70680e6ba07b4c2a

**Comment by kevinpapst** [comment]
Hm, I think we are talking about different things. I thought that you said in #763 that I should copy the new Dockerfile for the dev image into the Kimai repo.
But your gist looks like the Dockerfile which is already existing in here.

My assumption was, that I should copy & paste this Dockerfile:
https://github.com/tobybatch/kimai2/blob/master/Dockerfile
into the kimai 2 repository here. Was that a misunderstading?

**Comment by tobybatch** [comment]
The gist should replace the one in your repo, totally.  It uses a build stage to in line the kimai base into the kimai dev image build process.  This means you have the whole build change in a single file and removes dependencies on external resources.

It is hand crafted for your repo at the moment.  I'll add a build process into the docker repos when I get a sec.

**Comment by kevinpapst** [comment]
Alright, after having a look at the diff it is clearer, updated.

**Pull request merged**
