### PR TITLE
Dutch translation files

### PR DESCRIPTION
**Pull request by 1willem**
Reason for this pull request:

Adding the Dutch language (.nl.xliff) to Kimai2.
I translated the language files in the folder translations, as attached below. I assume some more files need to be translated. Can you tell me which files also need translation (log in screen, the error message when typing only one or two characters in the search bar, ... ?) and what other changes I need to make to implement Dutch language into Kimai?

Thanks for guiding me.

Willem

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks @1willem 👍 

Can you have a look at the documentation, so we can include dutch in 1.6?!
https://www.kimai.org/documentation/translations.html#adding-a-new-language

I will help with the frontend locales and the configurations once you are done with the basic translations.

**Comment by 1willem** [comment]
I read the documentation, Kevin. I assume you are waiting for the other files described in there:  

*AdminLTEBundle.nl.xliff* (this is the unchanged version uploaded by Noun 5 months ago, which I have just checked and approuved)  
*kimai.yaml* (I added nl date format)  
*services.yaml*  
*app.js*  
*calendar.js*  

I adjusted them (except for the AdminLTEBundle) and will add them here (to be able to upload, I had to add the .txt extension to all of the files; so remove that first).

I'm still wondering where to find some error messages that I couldn't locate in the translation files, for instance when inserting a too short search query in the search bar, the German language states: "Diese Zeichenkette ist zu kurz. Sie sollte mindestens 3 Zeichen haben." But I don't know in which file this translation is located. Another example: when entering an incorrect value in the Duration field, German language states: "Dieser Wert ist nicht gültig.". These (and others?) I don't know where to find.

I wanted to search for missing translations with the *bin/console* command, but I didn't manage to find how it works. I installed the [kimai2-cmd](https://github.com/infeeeee/kimai2-cmd/releases/tag/1.0.0) of infeeeee but it closes down each time I enter a command.

Willem

[AdminLTEBundle.nl.xliff.txt](https://github.com/kevinpapst/kimai2/files/3856062/AdminLTEBundle.nl.xliff.txt)
[app.js.txt](https://github.com/kevinpapst/kimai2/files/3856063/app.js.txt)
[calendar.js.txt](https://github.com/kevinpapst/kimai2/files/3856064/calendar.js.txt)
[kimai.yaml.txt](https://github.com/kevinpapst/kimai2/files/3856065/kimai.yaml.txt)
[services.yaml.txt](https://github.com/kevinpapst/kimai2/files/3856066/services.yaml.txt)

**Comment by kevinpapst** [comment]
I updated your changes with the configs and installed the version here:
http://demo-branch.kimai.org/nl/

After login with `susan_super` and `kitten` you can change the user language and test everything.

**Comment by 1willem** [comment]
I tested it with susan_super, Kevin. Everything seems to be correct. I even checked the error messages and they are implemented now. I cannot find anything missing. So all is good to go!

**Comment by kevinpapst** [comment]
Awesome, thanks for you contribution @1willem 🎉

**Pull request merged**
